
### 1.CONFIG: PORT, CONTEXT PATH ###
#server.servlet.context-path: /zuul
server:
  port: ${PORT:8081}
  error:
    include-message: always
###2. CONFIG: SPRING, SPRING ADMIN ###
spring:
  application:
    name: ${APP_NAME:TEMPLATE-API}
  datasource:
    url: jdbc:oracle:thin:@${DB_DATASOURCE:192.168.100.25:1521/orcl}
    username: ${DB_USERNAME:hadb1}
    password: ${DB_PASSWORD:haha@2512}
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        proc:
          param_null_passing: true
    show-sql: true
    hibernate:
      ddl-auto: validate #update/validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
### 3. CONFIG: MANAGEMENT ###
#https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2.0-M3-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default
#management.security.enabled=false
#management.endpoints.web.cors.allowed-origins=https://example.com
#management.endpoints.web.cors.allowed-methods=GET,POST
#management.shutdown.enabled=true
management:
  endpoints:
    enabledByDefault: true
    web:
      exposure:
        include: '*'
  health:
    mail:
      enabled: false
    kafka:
      enabled: false
  auditevents:
    enabled: true
  trace:
    http:
      enabled: true
### 4. CONFIG: LOGGING ###
logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 1MB
    max-history: 2
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
### 5. CONFIG: EUREKA ###
#eureka.instance.leaseRenewalIntervalInSeconds: 10
#eureka.client.registryFetchIntervalSeconds: 5
eureka:
  client:
    enabled: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${REGISTRY_EUREKA_SERVER_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true
    #ipAddress: ${KUBERNETES_SERVER_IP:10.0.222.33}
zuul:
  allowedOrigins: '*'
### 5. CONFIG: CUSTOM ###
app:
  current-app:
    api-key: ${API_KEY:19001000}
    check-api-key-for-external-api: '#'
    app-code: TEMPLATE
    app-name: TEMPLATE (TEMPLATE)
  guava-cache:
    expire-after-write-minutes-category-common: 2
    maximum-size-category-common: 5000
    menu-back-end-by-jwt-expire-after-write-minutes: 60
    menu-back-end-by-jwt-maximum-size: 5000
  paging:
    default-page-number: 0
    default-page-size: 20
    max-page-size: 100
  restapi:
    api-url-auth: ${ETC_CUSTOMS_AUTH_WEBAPI_API_URL:http://10.0.222.58/gateway/cate/api/auth}
    api-key-auth: ${ETC_CUSTOMS_AUTH_WEBAPI_API_KEY:19001000}
    close-idle-connections-in-ms: 180000
    connect-timeout-in-ms: 60000
    connection-manager-shutdown-in-ms: 300000
    max-connection: 1000
    max-per-route: 100
