### 1.CONFIG: PORT, CONTEXT PATH ###
#server.servlet.context-path: /zuul
server:
  port: ${PORT:8081}
  error:
    include-message: always
###2. CONFIG: SPRING, SPRING ADMIN ###
spring:
  application:
    name: ${APP_NAME:TEMPLATE-API}
  datasource:
#    url: jdbc:oracle:thin:@${DB_DATASOURCE:10.0.222.29:1521/ccs4db}
#    username: ${DB_USERNAME:DEMO}
#    password: ${DB_PASSWORD:123456}
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//10.0.223.163:1521/bcadb}
    username: ${SPRING_DATASOURCE_USERNAME:C08_DKX_OTO}
    password: ${SPRING_DATASOURCE_PASSWORD:Etcadmin1}
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        proc:
          param_null_passing: true
    show-sql: true
    hibernate:
      ddl-auto: validate #update/validate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


### 3. CONFIG: MANAGEMENT ###
#https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2.0-M3-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default
#management.security.enabled=false
#management.endpoints.web.cors.allowed-origins=https://example.com
#management.endpoints.web.cors.allowed-methods=GET,POST
#management.shutdown.enabled=true

management:
  endpoints:
    enabledByDefault: true
    web:
      exposure:
        include: '*'
  health:
    mail:
      enabled: false
    kafka:
      enabled: false
  auditevents:
    enabled: true
  trace:
    http:
      enabled: true
### 4. CONFIG: LOGGING ###
logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 1MB
    max-history: 2
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
### 5. CONFIG: EUREKA ###
#eureka.instance.leaseRenewalIntervalInSeconds: 10
#eureka.client.registryFetchIntervalSeconds: 5
eureka:
  client:
    enabled: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${REGISTRY_EUREKA_SERVER_URL:http://localhost:8761}/eureka/
  instance:
    preferIpAddress: true
    #ipAddress: ${KUBERNETES_SERVER_IP:10.0.222.33}
zuul:
  allowedOrigins: '*'
### 5. CONFIG: CUSTOM ###
app:
  current-app:
    api-key: ${APP_CURRENT_APP_API_KEY:19001000}
    check-api-key-for-external-api: '#'
    app-code: ${APP_CURRENT_APP_APP_CODE:EVISA}
    app-name: Evisa
  restapi:
    api-url-auth: ${APP_RESTAPI_API_URL_AUTH:http://10.0.223.64/evisa/develop/iam/cate/api/auth}
    api-key-auth: ${APP_RESTAPI_API_KEY_AUTH:19001000}
    close-idle-connections-in-ms: 180000
    connect-timeout-in-ms: ${RESTTEMPLATE_CONNECT_TIMEOUT:6000}
    read-timeout-in-ms: ${RESTTEMPLATE_READ_TIMEOUT:6000}
    connection-manager-shutdown-in-ms: 300000
    max-connection: 1000
    max-per-route: 100
    template-api: ${TEMPLATE_API:http://10.0.223.64/evisa/develop/template/api/v1/template/docx/render}
    iam-api: ${IAM_API:http://10.0.223.64/evisa/develop/iam/cate/v1}
    dmdc:
      url: ${DMDC_API_URL:http://10.0.223.64/evisa/develop/dmdc/api/v1}
      headers:
        token: ${API_HEADER_TOKEN:eyJhbGciOiJIUzUxMiJ9.ZXlKNmFYQWlPaUpFUlVZaUxDSmhiR2NpT2lKa2FYSWlMQ0psYm1NaU9pSkJNVEk0UTBKRExVaFRNalUySW4wLi5iS2poUldQaHF3SXo0QVJWQXRhbjBBLlVjQkRsN3FnMEJzZWtlWVVIZjNFQVFUSlM3Vmo0cTluNnI4SUs3UVdmNGNmRDZ4VWprVXlIY0tkcFhiNWFZQXA3eDFGU3AxUDNqRVk3WWt0ZUpZSGNra1h5TXZVUnE2RC1jYkpRRjBnVUEwM0RuSS16cmxVSGNIMHZsczZhMVdDRkFOeU9EMEluMC0yN1RZVDZRWl9YU0tESDQzcFVrSElhNkVFbk80dDhqZV93SzFkZGlHVWp3d3dUSDlaQklOYUp6eFlIWlNYbUFxZUZ6MGZhUEdFVmdjUEZ1cUNWSTQ2a2lzYXRKN3NFVWcubDE2Qk1JTlhDMktETlozSkpzXzgtZw==.L8OVDCdahrgyHwpQJTVcUTkb3waTrVQDy7kStzS1z99dNSQ6DCcoJeHREZQcVnthAp14M3TUrLXSd8P_JpCh_A}
#  security:
#    enable-bypass-permissions: ${APP_SECURITY_ENABLE_BYPASS_PERMISSIONS:true}



config:
  digital-signature:
    is-verify: ${IS_VERIFY_DIGITAL_SIGNATURE:true}
    text-sign: ${TEXT_DS_SIGN:VITRIDATCHUKYSO}
  document:
    input-type: ${DOCUMENT_TYPE:json}
    folder:
      input-path: ${DOCUMENT_INPUT_PATH:/data/input}
      input-image-path: ${DOCUMENT_INPUT_IMAGE_PATH:/data/image}
      imported-path: ${DOCUMENT_IMPORTED_PATH:/data/imported}
      output-path: ${DOCUMENT_OUTPUT_PATH:/data/output}
  storage:
    #    bucket:
    #      evisa-bucket: ${STORAGE_BUCKET:hhh}
    #      evisa-image-path: ${STORAGE_IMAGE_PATH:auto}
    #      evisa-ho-so-chap-thuan: ${STORAGE_HO_SO_CHAP_THUAN:ky-so/chap-thuan}
    #      evisa-ho-so-tu-choi: ${STORAGE_HO_SO_TU_CHOI:ky-so/tu-choi}
    #      evisa-ky-so-huy: ${STORAGE_HO_SO_HUY:ky-so/huy-thi-thuc}
    #      evisa-signing-path: ${STORAGE_SIGNING_PATH:sign/}
    #    access:
    #      key: ${STORAGE_ACCESS_KEY:hhh@12345}
    #      #      Pass: Etc@1234
    #      secret: ${STORAGE_ACCESS_SECRET:hhh@12345}
    #    url: ${STORAGE_URL:https://127.0.0.1:9000}
    url: http://10.0.222.153:9000
    accessKey: xlvp-api
    secretKey: GIVJ0nE2gCenOwXWyfJwSpd0NjaP5V79
    buckets:
        public: xlvp-public
        private: xlvp
