/*==============================================================*/
/* Table: item */
/*==============================================================*/
CREATE TABLE XXX
(
    itemId      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    itemCode    VARCHAR2(30 CHAR),
    itemName    VARCHAR2(30 CHAR),
    description VARCHAR2(50 CHAR)
)

create table customer
(
    customerId   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customerName VARCHAR2(30 CHAR),
    customerDC   VARCHAR2(30 CHAR)
)
